default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: <%= ENV['POSTGRES_HOST'] %>

  development:
    <<: *default
    database: sport_app_development

  test:
    <<: *default
    database: sport_app_test
    host: localhost

  production:
    <<: *default
    database: sport_app_production
    username: sport_app
    password: <%= ENV['SPORT_APP_DATABASE_PASSWORD'] %>
